var strings = {
best: "Best",
buttonOK: "OK",
buttonCancel: "Cancel",
buttonClose: "Close",
buttonEnter: "Enter",
buttonFind: "Find",
collapseTree: "Collapse Tree",
differences: "Differences",
differencesCalculating: "Please wait, calculating differences...",
differencesErrorNodiffs: "There were no differences found between the selected {0}",
differencesSelectLabel: "Select {0}:",
entity: "Entity",
entities: "Entities",
entitiesDiscarded: "Entities Descartadas",
entitiesDiscardedCount: "Entities Descartadas: {0}",
entitiesRemaining: "Entities Remaining",
entitiesRemainingCount: "Entities Remaining: {0}",
entityThumbnails: "Entity Thumbnails",
expandTree: "Expand Tree",
feature: "Feature",
features: "Features",
featuresAvailable: "Features Available",
featuresAvailableCount: "Features Available: {0}",
featuresChosen: "Features Chosen",
featuresChosenCount: "Features Chosen: {0}",
featureThumbnails: "Feature Thumbnails",
find: "Find",
findErrorInvalidInput: "Invalid Search Text",
findLabel: "Find:",
findOptionCaseSensitive: "Case sensitive",
findOptionWholeWord: "Whole word",
findNoMatches: "No matches found",
findTitleItemType: "Search {0}",
help: "Help",
home: "Home",
matchValue: "{0}%",
noCaption: "No Caption",
numericInput: "Numeric Input",
enterObservedValue: "Enter observed value",
enterObservedValueUnits: "Enter your observed value, where units: {0}",
numericInputRange: "Values for the remaining {0} should be between {1} and {2}",
numericInputRangeNone: "Warning, this {0} no longer applies to the remaining {1}, try pruning",
preferences: "Preferences",
prune: "Prune",
removed: "Removed",
restart: "Restart",
restored: "Restored",
statusCalculatingBestFeatures: "Please wait, calculating best {0}...",
statusBestFeature: "Best {0}: {1}",
statusBestNotFound: "Sorry, no best {0} were found",
statusPruning: "Please wait, pruning redundant {0}...",
statusPruneResult: "{0} redundant {1} pruned",
statusRestartingKey: "Please wait, restarting key...",
statusKeyInitialised: "Key initialised, {0} {1} remaining",
statusKeyRestarted: "Key restarted, {0} {1} remaining",
statusEntitiesDiscarded: "{0} {1} discarded, {2} remaining",
statusEntitiesRestored: "{0} {1} restored, {2} remaining",
shortcuts: "Shortcuts",
shortcutsNoFeatures: "There were no shortcut {0} found",
shortcutsTitle: "Shortcut {0}",
subsets: "Subsets",
subsetsFilteredMessage: "Note: filtered by {0}",
subsetsRestartMessage: "Selecting or changing {0} requires the key to be restarted, continue?",
subsetsRetainRestart: "Retain selected {0} on key restart?",
subsetsTitle: "Subsets",
whyDiscarded: "Why Discarded",
whyDiscardedCalculating: "Please wait, calculating why discarded...",
whyDiscardedErrorNoSelection: "Please select a discarded {0} and try again.",
whyDiscardedBecause: "was discarded because of your selections of the following {0}",
whyDiscardedDoesNotMatch: "also does not match your selections for the following {0}",
whyDiscardedKeySays: "Key says",
whyDiscardedYouChose: "You chose",
treeLoading: "Loading...",
};